export const initialPlaylist = [
  {
    id: 1,
    title: "Feliz Cumpleaños",
    artist: "Las Mananitas",
    youtubeUrl: "https://www.youtube.com/watch?v=Xn59trCP0wI",
    youtubeId: "Xn59trCP0wI",
    lyrics: `Muy felices te queremos
con amor y alegría
que cumplas muchos años más
en tu día
Feliz cumpleaños Mamita`,
    tags: ["traditional", "mexican", "celebration", "birthday"],
  },
  {
    id: 2,
    title: "Cielito Lindo",
    artist: "Jorge A. Marrón",
    youtubeUrl: "https://www.youtube.com/watch?v=Lp-X3UfNqO0",
    youtubeId: "Lp-X3UfNqO0",
    lyrics: `Cielito lindo, cielito lindo
de mi corazón
Cielito lindo que tienes alma de luz`,
    tags: ["traditional", "mexican", "folk"],
  },
  {
    id: 3,
    title: "3 AM",
    artist: "Jesse & Joy",
    youtubeUrl: "https://www.youtube.com/watch?v=y_m_O6Z9xZ8",
    youtubeId: "y_m_O6Z9xZ8",
    lyrics: null,
    tags: ["pop", "dance", "upbeat"],
  },
  {
    id: 4,
    title: "Me Voy",
    artist: "Jesse & Joy",
    youtubeUrl: "https://www.youtube.com/watch?v=p079pPz6p3c",
    youtubeId: "p079pPz6p3c",
    lyrics: null,
    tags: ["pop", "romantic", "ballad"],
  },
  {
    id: 5,
    title: "¡Viva La Vida!",
    artist: "Coldplay",
    youtubeUrl: "https://www.youtube.com/watch?v=dvgZkm1xWPE",
    youtubeId: "dvgZkm1xWPE",
    lyrics: null,
    tags: ["rock", "anthemic", "energetic"],
  },
  {
    id: 6,
    title: "Happy Birthday",
    artist: "Stevie Wonder",
    youtubeUrl: "https://www.youtube.com/watch?v=QwOU3Guu7x4",
    youtubeId: "QwOU3Guu7x4",
    lyrics: null,
    tags: ["soul", "birthday", "fun"],
  },
  {
    id: 1776954694042,
    title: "De carne y hueso",
    artist: "MDolores Pradera",
    youtubeUrl: "https://www.youtube.com/watch?v=fNzpOdmPfA0",
    youtubeId: "fNzpOdmPfA0",
    lyrics: null,
    tags: ["ballad", "traditional", "slow", "spanish"],
  },
  {
    id: 1776954809739,
    title: "La Flor de la canela",
    artist: "MDolores Pradera",
    youtubeUrl: "https://www.youtube.com/watch?v=U22NbxoX7zI",
    youtubeId: "U22NbxoX7zI",
    lyrics: null,
    tags: ["ballad", "traditional", "slow", "spanish"],
  },
  {
    id: 1776954934456,
    title: "Habaneras de Cádiz",
    artist: "MDolores Pradera",
    youtubeUrl: "https://www.youtube.com/watch?v=ANZIKv-5LQQ",
    youtubeId: "ANZIKv-5LQQ",
    lyrics: null,
    tags: ["ballad", "traditional", "mid-tempo", "spanish"],
  },
  {
    id: 1776954984269,
    title: "Toda una vida",
    artist: "MDolores Pradera",
    youtubeUrl: "https://www.youtube.com/watch?v=sNmIpe_QAEg",
    youtubeId: "sNmIpe_QAEg",
    lyrics: null,
    tags: ["ballad", "traditional", "slow", "spanish"],
  },
  {
    id: 1776955065634,
    title: "María la portuguesa",
    artist: "MDolores Pradera y Carlos Cano",
    youtubeUrl: "https://www.youtube.com/watch?v=WdaChGT4ZFg",
    youtubeId: "WdaChGT4ZFg",
    lyrics: null,
    tags: ["ballad", "fado", "slow", "spanish"],
  },
  {
    id: 1776955123434,
    title: "Alma, corazón y vida",
    artist: "MDolores Pradera",
    youtubeUrl: "https://www.youtube.com/watch?v=NYy178y8c4Q",
    youtubeId: "NYy178y8c4Q",
    lyrics: null,
    tags: ["ballad", "traditional", "slow", "spanish"],
  },
  {
    id: 1776955207517,
    title: "Lágrimas negras",
    artist: "MDolores Pradera",
    youtubeUrl: "https://www.youtube.com/watch?v=X_7_BKUZrH4",
    youtubeId: "X_7_BKUZrH4",
    lyrics: null,
    tags: ["ballad", "bolero", "slow", "spanish"],
  },
  {
    id: 1776955365920,
    title: "Amarraditos",
    artist: "MDolores Pradera",
    youtubeUrl: "https://www.youtube.com/watch?v=fWftBBeMGsg",
    youtubeId: "fWftBBeMGsg",
    lyrics: null,
    tags: ["ballad", "traditional", "slow", "spanish"],
  },
  {
    id: 1776955433884,
    title: "Negra mía",
    artist: "MDolores Pradera",
    youtubeUrl: "https://www.youtube.com/watch?v=eLKFXNPCueQ",
    youtubeId: "eLKFXNPCueQ",
    lyrics: null,
    tags: ["ballad", "traditional", "slow", "spanish"],
  },
  {
    id: 1776955541851,
    title: "Luz de luna",
    artist: "MDolores Pradera",
    youtubeUrl: "https://www.youtube.com/watch?v=3YVIPy2v0OQ",
    youtubeId: "3YVIPy2v0OQ",
    lyrics: null,
    tags: ["ballad", "traditional", "slow", "spanish"],
  },
  {
    id: 1776955625732,
    title: "La hija de Don Juan Alba",
    artist: "MDolores Pradera",
    youtubeUrl: "https://www.youtube.com/watch?v=2__MTO0eXB4",
    youtubeId: "2__MTO0eXB4",
    lyrics: null,
    tags: ["ballad", "traditional", "slow", "spanish"],
  },
  {
    id: 1776955779836,
    title: "Qué te vaya bonito",
    artist: "MDolores Pradera",
    youtubeUrl: "https://www.youtube.com/watch?v=gl5J0ZK7zCA",
    youtubeId: "gl5J0ZK7zCA",
    lyrics: null,
    tags: ["ballad", "traditional", "slow", "spanish"],
  },
  {
    id: 1776955836518,
    title: "Caballo viejo",
    artist: "MDolores Pradera",
    youtubeUrl: "https://www.youtube.com/watch?v=YPjBlSP_OLU",
    youtubeId: "YPjBlSP_OLU",
    lyrics: null,
    tags: ["ballad", "traditional", "mid-tempo", "spanish"],
  },
  {
    id: 1776956020635,
    title: "Fina Estampa",
    artist: "MDolores Pradera",
    youtubeUrl: "https://www.youtube.com/watch?v=xvKfN-kNkZg",
    youtubeId: "xvKfN-kNkZg",
    lyrics: null,
    tags: ["ballad", "traditional", "mid-tempo", "spanish"],
  },
  {
    id: 1776956294769,
    title: "Gracias a la vida",
    artist: "Mercedes Sosa",
    youtubeUrl: "https://www.youtube.com/watch?v=qR4fwenppPQ",
    youtubeId: "qR4fwenppPQ",
    lyrics: null,
    tags: ["folk", "traditional", "slow", "argentinian"],
  },
  {
    id: 1776957249737,
    title: "Gracias a la vida",
    artist: "Mercedes Sosa y Joan Baez",
    youtubeUrl: "https://www.youtube.com/watch?v=rMuTXcf3-6A",
    youtubeId: "rMuTXcf3-6A",
    lyrics: null,
    tags: ["folk", "traditional", "slow", "international"],
  },
  {
    id: 1776957501106,
    title: "Donna donna",
    artist: "Joan Baez",
    youtubeUrl: "https://www.youtube.com/watch?v=TjQCFwd6JuI",
    youtubeId: "TjQCFwd6JuI",
    lyrics: null,
    tags: ["folk", "acoustic", "slow", "english"],
  },
  {
    id: 1776957571887,
    title: "Forever young",
    artist: "Joan Baez",
    youtubeUrl: "https://www.youtube.com/watch?v=-4UoJ47SzjA",
    youtubeId: "-4UoJ47SzjA",
    lyrics: null,
    tags: ["folk", "ballad", "mid-tempo", "english"],
  },
  {
    id: 1776957704771,
    title: "Hallelujah",
    artist: "Leonard Cohen",
    youtubeUrl: "https://www.youtube.com/watch?v=YrLk4vdY28Q",
    youtubeId: "YrLk4vdY28Q",
    lyrics: null,
    tags: ["folk", "slow", "melancholy", "english"],
  },
  {
    id: 1776958159257,
    title: "La llorona",
    artist: "Joan Baez",
    youtubeUrl: "https://www.youtube.com/watch?v=_-F8GxI0t7I",
    youtubeId: "_-F8GxI0t7I",
    lyrics: null,
    tags: ["folk", "traditional", "slow", "mexican"],
  },
  {
    id: 1776958296340,
    title: "House of the raising sun",
    artist: "Joan Baez",
    youtubeUrl: "https://www.youtube.com/watch?v=NkyYHYUcGgo",
    youtubeId: "NkyYHYUcGgo",
    lyrics: null,
    tags: ["folk", "traditional", "mid-tempo", "english"],
  },
  {
    id: 1776958520971,
    title: "Blowing in the wind",
    artist: "Bob Dylan",
    youtubeUrl: "https://www.youtube.com/watch?v=KJBbX0jzM2c",
    youtubeId: "KJBbX0jzM2c",
    lyrics: null,
    tags: ["folk", "rock", "mid-tempo", "english"],
  },
  {
    id: 1776958678639,
    title: "The House of the Rising Sun",
    artist: "Joan Baez",
    youtubeUrl: "https://www.youtube.com/watch?v=NkyYHYUcGgo",
    youtubeId: "NkyYHYUcGgo",
    lyrics: null,
    tags: ["folk", "traditional", "mid-tempo", "english"],
  },
  {
    id: 1776958782656,
    title: "Farewll Angelina",
    artist: "Joan Baez",
    youtubeUrl: "https://www.youtube.com/watch?v=1fcEd38XQU8",
    youtubeId: "1fcEd38XQU8",
    lyrics: null,
    tags: ["folk", "acoustic", "slow", "english"],
  },
  {
    id: 1776973289726,
    title: "Knocking on the heavens doors",
    artist: "Bob Dylan",
    youtubeUrl: "https://www.youtube.com/watch?v=z4R5crZylQ0",
    youtubeId: "z4R5crZylQ0",
    lyrics: null,
    tags: ["folk", "rock", "slow", "english"],
  },
  {
    id: 1777116283094,
    title: "Alfonsina y el Mar",
    artist: "Los sabandeños",
    youtubeUrl: "https://www.youtube.com/watch?v=2cmbj9kwbx0",
    youtubeId: "2cmbj9kwbx0",
    lyrics: null,
    tags: ["folk", "traditional", "slow", "canarian"],
  },
  {
    id: 1777116343094,
    title: "Molinedo Cafe",
    artist: "Los Sabandeños",
    youtubeUrl: "https://www.youtube.com/watch?v=BlHhyGyplbk",
    youtubeId: "BlHhyGyplbk",
    lyrics: null,
    tags: ["folk", "traditional", "mid-tempo", "canarian"],
  },
  {
    id: 1777116425942,
    title: "Historia de un Amor",
    artist: "Los Sabandeños",
    youtubeUrl: "https://www.youtube.com/watch?v=Mu6RHrziy68",
    youtubeId: "Mu6RHrziy68",
    lyrics: null,
    tags: ["folk", "traditional", "slow", "canarian"],
  },
  {
    id: 1777116537026,
    title: "Perfidia",
    artist: "Los Sabandeños",
    youtubeUrl: "https://www.youtube.com/watch?v=QWHs5uuap-Y",
    youtubeId: "QWHs5uuap-Y",
    lyrics: null,
    tags: ["folk", "traditional", "slow", "canarian"],
  },
  {
    id: 1777116649877,
    title: "Guantanamera",
    artist: "Los Sabandeños",
    youtubeUrl: "https://www.youtube.com/watch?v=2Q5kl8ZxuvI",
    youtubeId: "2Q5kl8ZxuvI",
    lyrics: null,
    tags: ["folk", "traditional", "mid-tempo", "canarian"],
  },
  {
    id: 1777117017278,
    title: "Perdoname",
    artist: "El Duo dinámico",
    youtubeUrl: "https://www.youtube.com/watch?v=uS6E-KKh4CE",
    youtubeId: "uS6E-KKh4CE",
    lyrics: null,
    tags: ["pop", "rock-n-roll", "upbeat", "60s"],
  },
  {
    id: 1777117055476,
    title: "Resistiré",
    artist: "El Duo Dinámico",
    youtubeUrl: "https://www.youtube.com/watch?v=DpQyuMPrhog",
    youtubeId: "DpQyuMPrhog",
    lyrics: null,
    tags: ["pop", "rock-n-roll", "upbeat", "60s"],
  },
  {
    id: 1777117243993,
    title: "El Cielo está dentro de mí",
    artist: "Atahualpa Yupanqui",
    youtubeUrl: "https://www.youtube.com/watch?v=v0YqCLfbkcY",
    youtubeId: "v0YqCLfbkcY",
    lyrics: null,
    tags: ["folk", "guitar", "slow", "argentinian"],
  },
  {
    id: 1777117371674,
    title: "Le tengo rabia al silencio",
    artist: "Atahualpa Yupanqui",
    youtubeUrl: "https://www.youtube.com/watch?v=DfQl1TPQAxc",
    youtubeId: "DfQl1TPQAxc",
    lyrics: null,
    tags: ["folk", "guitar", "slow", "argentinian"],
  },
  {
    id: 1777117449592,
    title: "Gracias a la Vida",
    artist: "Violeta Parra",
    youtubeUrl: "https://www.youtube.com/watch?v=Y5KZSlUxBi8",
    youtubeId: "Y5KZSlUxBi8",
    lyrics: null,
    tags: ["folk", "traditional", "slow", "chilean"],
  },
  {
    id: 1777121053090,
    title: "Albertío",
    artist: "Violeta Parra",
    youtubeUrl: "https://www.youtube.com/watch?v=zE13TMrHeFk",
    youtubeId: "zE13TMrHeFk",
    lyrics: null,
    tags: ["folk", "traditional", "mid-tempo", "chilean"],
  },
  {
    id: 1777121984208,
    title: "Cielo",
    artist: "Violeta Parra",
    youtubeUrl: "https://www.youtube.com/watch?v=X--Kxt2KwEQ",
    youtubeId: "X--Kxt2KwEQ",
    lyrics: null,
    tags: ["folk", "traditional", "slow", "chilean"],
  },
  {
    id: 1777122064420,
    title: "Lcuenca de los poetas",
    artist: "Violeta Parra",
    youtubeUrl: "https://www.youtube.com/watch?v=9RQdP3Y12r0",
    youtubeId: "9RQdP3Y12r0",
    lyrics: null,
    tags: ["folk", "traditional", "mid-tempo", "chilean"],
  },
  {
    id: 1777122116268,
    title: "Volver a los diecisiete",
    artist: "Violeta Parra",
    youtubeUrl: "https://www.youtube.com/watch?v=2ozG2tjy3QM",
    youtubeId: "2ozG2tjy3QM",
    lyrics: null,
    tags: ["folk", "traditional", "slow", "chilean"],
  },
  {
    id: 1777122518105,
    title: "De cuerpo entero",
    artist: "Violeta Parra",
    youtubeUrl: "https://www.youtube.com/watch?v=pu-rOSpaRTg",
    youtubeId: "pu-rOSpaRTg",
    lyrics: null,
    tags: ["folk", "traditional", "mid-tempo", "chilean"],
  },
  {
    id: 1777122570836,
    title: "15 años",
    artist: "El Duo dinámico",
    youtubeUrl: "https://www.youtube.com/watch?v=e0E9geFbuFU",
    youtubeId: "e0E9geFbuFU",
    lyrics: null,
    tags: ["pop", "rock-n-roll", "upbeat", "60s"],
  },
  {
    id: 1777122645003,
    title: "Amor misterioso",
    artist: "El Duo Dinámico",
    youtubeUrl: "https://www.youtube.com/watch?v=PV9zPUSwTjk",
    youtubeId: "PV9zPUSwTjk",
    lyrics: null,
    tags: ["pop", "rock-n-roll", "mid-tempo", "60s"],
  },
  {
    id: 1777122900587,
    title: "El final del verano",
    artist: "El Duo Dinámico",
    youtubeUrl: "https://www.youtube.com/watch?v=gbKAOFBgR8U",
    youtubeId: "gbKAOFBgR8U",
    lyrics: null,
    tags: ["pop", "rock-n-roll", "slow", "60s"],
  },
  {
    id: 1777123330488,
    title: "Robaré",
    artist: "El Duo Dinámico",
    youtubeUrl: "https://www.youtube.com/watch?v=3gBBRf_P-Wk",
    youtubeId: "3gBBRf_P-Wk",
    lyrics: null,
    tags: ["pop", "rock-n-roll", "upbeat", "60s"],
  },
  {
    id: 1777123512603,
    title: "Eres tú",
    artist: "El Duo Dinámico",
    youtubeUrl: "https://www.youtube.com/watch?v=OVWxDLvT8S0",
    youtubeId: "OVWxDLvT8S0",
    lyrics: null,
    tags: ["pop", "rock-n-roll", "slow", "60s"],
  },
  {
    id: 1777123953504,
    title: "Guateque 1",
    artist: "El Duo Dinámico",
    youtubeUrl: "https://www.youtube.com/watch?v=zIh3K2GH1lo",
    youtubeId: "zIh3K2GH1lo",
    lyrics: null,
    tags: ["pop", "rock-n-roll", "upbeat", "60s"],
  },
  {
    id: 1777124242938,
    title: "La Plaga",
    artist: "El Duo Dinámico",
    youtubeUrl: "https://www.youtube.com/watch?v=iQAdYc6Ygag",
    youtubeId: "iQAdYc6Ygag",
    lyrics: null,
    tags: ["pop", "rock-n-roll", "upbeat", "60s"],
  },
  {
    id: 1777126109341,
    title: "Medley Rock",
    artist: "El Duo Din;amico",
    youtubeUrl: "https://www.youtube.com/watch?v=y3vArllKohQ",
    youtubeId: "y3vArllKohQ",
    lyrics: null,
    tags: ["pop", "rock-n-roll", "upbeat", "60s"],
  },
  {
    id: 1777126584968,
    title: "Esos ojitos negros",
    artist: "El Duo Din'amico",
    youtubeUrl: "https://www.youtube.com/watch?v=VY4L7JrdyOM",
    youtubeId: "VY4L7JrdyOM",
    lyrics: null,
    tags: ["pop", "rock-n-roll", "mid-tempo", "60s"],
  },
  {
    id: 1777126670219,
    title: "Perdoname y Esos ojos negros",
    artist: "El Duo Dinámico",
    youtubeUrl: "https://www.youtube.com/watch?v=mPkqbmxaWl8",
    youtubeId: "mPkqbmxaWl8",
    lyrics: null,
    tags: ["pop", "rock-n-roll", "mid-tempo", "60s"],
  },
  {
    id: 1777128928637,
    title: "Guateque 3",
    artist: "El Duo Dinámico",
    youtubeUrl: "https://www.youtube.com/watch?v=r-vNrjpjvN4",
    youtubeId: "r-vNrjpjvN4",
    lyrics: null,
    tags: ["pop", "rock-n-roll", "upbeat", "60s"],
  },
  {
    id: 1777129302803,
    title: "Eres tú",
    artist: "El Duo Dinámico",
    youtubeUrl: "https://www.youtube.com/watch?v=oiAuXrauO1M",
    youtubeId: "oiAuXrauO1M",
    lyrics: null,
    tags: ["pop", "rock-n-roll", "slow", "60s"],
  },
  {
    id: 1780426307432,
    title: "It's not unusual",
    artist: "Tom Jones",
    youtubeUrl: "https://www.youtube.com/watch?v=nagjPyNMu9Q&list=RDnagjPyNMu9Q&start_radio=1",
    youtubeId: "nagjPyNMu9Q",
    lyrics: null,
    tags: ["user-added", "energetic", "upbeat", "energetic", "fast"],
  },
  {
    id: 1780426367479,
    title: "She's a lady",
    artist: "Tom Jones",
    youtubeUrl: "https://www.youtube.com/watch?v=3wXiVPxFJVE&list=RD3wXiVPxFJVE&start_radio=1",
    youtubeId: "3wXiVPxFJVE",
    lyrics: null,
    tags: ["user-added", "energetic", "upbeat", "energetic", "fast"],
  },
  {
    id: 1780426477478,
    title: "She's a lady",
    artist: "Tom Jones & Paul Anka",
    youtubeUrl: "https://www.youtube.com/watch?v=rhp2SyuSb-o&list=RDrhp2SyuSb-o&start_radio=1",
    youtubeId: "rhp2SyuSb-o",
    lyrics: null,
    tags: ["user-added", "energetic", "upbeat", "energetic", "fast"],
  },
  {
    id: 1780426556062,
    title: "Delillah",
    artist: "Tom Jones",
    youtubeUrl: "https://www.youtube.com/watch?v=1fpT6ERcH38&list=RD1fpT6ERcH38&start_radio=1",
    youtubeId: "1fpT6ERcH38",
    lyrics: null,
    tags: ["user-added", "romantic", "romantic", "ballad", "slow"],
  },
  {
    id: 1780426706497,
    title: "Keep on running",
    artist: "Tom Jones",
    youtubeUrl: "https://www.youtube.com/watch?v=qeVMfZLzw2E&list=RDqeVMfZLzw2E&start_radio=1",
    youtubeId: "qeVMfZLzw2E",
    lyrics: null,
    tags: ["user-added", "energetic", "upbeat", "energetic", "fast"],
  },
  {
    id: 1780426797083,
    title: "Proud Mary",
    artist: "Tom Jones",
    youtubeUrl: "https://www.youtube.com/watch?v=qjKixv6i3U0&list=RDqjKixv6i3U0&start_radio=1",
    youtubeId: "qjKixv6i3U0",
    lyrics: null,
    tags: ["user-added", "energetic", "upbeat", "energetic", "fast"],
  },
  {
    id: 1780426911603,
    title: "Put your head on my shoulder",
    artist: "Paul Anka",
    youtubeUrl: "https://www.youtube.com/watch?v=zpGpu-pIVEk&list=RDzpGpu-pIVEk&start_radio=1",
    youtubeId: "zpGpu-pIVEk",
    lyrics: null,
    tags: ["user-added", "romantic", "romantic", "ballad", "slow"],
  },
  {
    id: 1780427087735,
    title: "Diana",
    artist: "Paul Anka",
    youtubeUrl: "https://www.youtube.com/watch?v=1Nie88qy6I4&list=PLA6Hzc1fA1DIFU_JxzIAsdpUbjI6lBmEw",
    youtubeId: "1Nie88qy6I4",
    lyrics: null,
    tags: ["user-added", "romantic", "romantic", "ballad", "slow"],
  },
  {
    id: 1780427494387,
    title: "My Way",
    artist: "Paul Anka",
    youtubeUrl: "https://www.youtube.com/watch?v=URs9GEGcn4E&list=RDURs9GEGcn4E&start_radio=1",
    youtubeId: "URs9GEGcn4E",
    lyrics: null,
    tags: ["user-added", "romantic", "romantic", "ballad", "slow"],
  },
  {
    id: 1780427608000,
    title: "Like a rolling stone",
    artist: "Bob Dylan",
    youtubeUrl: "https://www.youtube.com/watch?v=IwOfCgkyEj0&list=PLpTHjAucqq9A2IDIsR8Ftbg7U6bKCMrcr&index=2",
    youtubeId: "IwOfCgkyEj0",
    lyrics: null,
    tags: ["user-added", "nostalgic", "nostalgic", "retro", "classic"],
  },
  {
    id: 1780427698316,
    title: "Knockin' On Heaven's Door",
    artist: "Bob Dylan",
    youtubeUrl: "https://www.youtube.com/watch?v=rm9coqlk8fY&list=PLpTHjAucqq9A2IDIsR8Ftbg7U6bKCMrcr&index=6",
    youtubeId: "rm9coqlk8fY",
    lyrics: null,
    tags: ["user-added", "nostalgic", "nostalgic", "retro", "classic"],
  },
  {
    id: 1780427817550,
    title: "Blowinn the wind",
    artist: "Bob Dylan",
    youtubeUrl: "https://www.youtube.com/watch?v=MMFj8uDubsE&list=PLpTHjAucqq9A2IDIsR8Ftbg7U6bKCMrcr&index=11",
    youtubeId: "MMFj8uDubsE",
    lyrics: null,
    tags: ["user-added", "nostalgic", "nostalgic", "retro", "classic"],
  },
  {
    id: 1780427932649,
    title: "Mr Tambourine man",
    artist: "Bob Dylan",
    youtubeUrl: "https://www.youtube.com/watch?v=oecX_1pqxk0&list=PLpTHjAucqq9A2IDIsR8Ftbg7U6bKCMrcr&index=18",
    youtubeId: "oecX_1pqxk0",
    lyrics: null,
    tags: ["user-added", "nostalgic", "nostalgic", "retro", "classic"],
  },
];

export function getYoutubeEmbedUrl(videoId) {
  return `https://www.youtube.com/embed/${videoId}?autoplay=1&enablejsapi=1`;
}

export function extractYoutubeId(url) {
  if (!url) return null;
  const trimmedUrl = url.trim();
  const patterns = [
    /[?&]v=([a-zA-Z0-9_-]{11})/,
    /youtu\.be\/([a-zA-Z0-9_-]{11})/,
    /youtube\.com\/embed\/([a-zA-Z0-9_-]{11})/,
    /^([a-zA-Z0-9_-]{11})$/,
  ];
  for (const pattern of patterns) {
    const match = trimmedUrl.match(pattern);
    if (match && match[1]) return match[1];
  }
  return null;
}
